import { test, expect, type Page } from '@playwright/test';
const snapshot=(page:Page)=>page.evaluate(()=> (window as any).studio.getSnapshot());
async function commit(page:Page,revision:number){await expect.poll(async()=> (await snapshot(page)).lastCommit?.token.revision).toBe(revision);}
async function create(page:Page){await page.goto('/');expect(await page.evaluate(()=>crossOriginIsolated)).toBe(false);await page.getByRole('button',{name:'프로젝트 만들기'}).click();await commit(page,1);}
const frame=(page:Page)=>page.frameLocator('#preview iframe');
async function generate(page:Page,prompt='고객 목록 화면 만들어줘'){await page.getByLabel('만들고 싶은 화면').fill(prompt);await page.getByRole('button',{name:'보내기'}).click();await page.getByRole('button',{name:'아니요',exact:true}).click();await commit(page,2);}
async function save(page:Page,app:string){return page.evaluate(async app=>{const c=(window as any).studio;return c.saveFiles({...c.getSnapshot().project.files,'/src/App.tsx':app});},app);}
const plain=(text:string)=>`export default function App(){return <h1>${text}</h1>}`;
test('A: 생성, 역질문, 마스킹, 조회 사유와 감사 기록',async({page})=>{await create(page);await generate(page);await expect(frame(page).getByText('조회 사유', {exact:true})).toBeVisible();await frame(page).getByRole('button',{name:'조회',exact:true}).click();await expect(frame(page).getByRole('alert')).toBeVisible();await frame(page).getByLabel('조회 사유').fill('고객 문의 확인');await frame(page).getByRole('button',{name:'조회',exact:true}).click();await expect(frame(page).getByText('010-****-5678')).toBeVisible();await page.getByRole('button',{name:'활동 기록',exact:true}).click();await expect.poll(async()=>{await page.evaluate(()=> (window as any).studio.loadAudit());return (await snapshot(page)).audit.some((x:any)=>x.decision==='allowed'&&x.reason==='고객 문의 확인');}).toBe(true);await page.screenshot({path:'artifacts/studio.png',fullPage:true});});
test('B: 문법 오류는 마지막 정상 화면 유지',async({page})=>{await create(page);const original=await frame(page).locator('body').innerText();await page.getByLabel('소스 코드').fill('export default function App( {');await page.getByRole('button',{name:'저장하고 반영'}).click();await expect(page.getByRole('status')).toContainText('이전 화면을 유지했어요: 문법 오류');expect(await frame(page).locator('body').innerText()).toBe(original);expect((await snapshot(page)).lastCommit.token.revision).toBe(1);});
test('C: 이전 실행을 지연해도 최신 revision만 커밋',async({page})=>{await create(page);await save(page,`await new Promise(r=>setTimeout(r,2000));${plain('늦은 이전 화면')}`);await expect.poll(async()=> (await snapshot(page)).events.some((e:any)=>e.type==='build_started'&&e.token.revision===2)).toBe(true);await expect(page.locator('#preview iframe')).toHaveCount(2);await save(page,plain('가장 최신 화면'));await commit(page,3);await page.waitForTimeout(2400);await expect(frame(page).getByText('가장 최신 화면')).toBeVisible();const events=(await snapshot(page)).events;expect(events.filter((e:any)=>e.type==='committed'&&e.token.revision===2)).toHaveLength(0);expect(events.some((e:any)=>e.type==='stale_discarded'&&e.token.revision===2)).toBe(true);});
test('D: viewer 자체 발급 차단, 읽기 전용 차단, 제한된 쓰기 허용',async({page})=>{await create(page);await generate(page,'고객 목록 상태 변경 화면 만들어줘');
const attackCode=`const __cfg=globalThis.__TOI_FETCH_CONFIG__;
globalThis.__TOI_BOUNDARY_PROBE__=await Promise.all([
 ['/dev/session',{user:'generated-attacker',roles:['viewer','editor','platform-admin']}],
 ['/capabilities',{projectId:__cfg.projectId,mode:'write',env:'preview',apiIds:['customers'],ttlSec:60}]
].map(async ([endpoint,payload])=>{try {const r=await fetch('http://localhost:7200'+endpoint,{method:'POST',body:JSON.stringify(payload)});const body=await r.json();return {endpoint,status:r.status,tokenObtained:typeof body.token==='string',blocked:!r.ok};}catch{return {endpoint,tokenObtained:false,blocked:true};}}));
`;
// Run an adversarial generated module in the actual preview realm. This reaches
// the proxy boundary even when the agent-server rejects raw fetch at save time.
await frame(page).locator('body').evaluate(async (_element,code)=>{await import('data:text/javascript;charset=utf-8,'+encodeURIComponent(code));},attackCode);
const security=await frame(page).locator('body').evaluate(async()=>{const config=(globalThis as any).__TOI_FETCH_CONFIG__;const session=JSON.parse(atob(config.sessionToken.split('.')[1]));let blocked=false;try{const response=await fetch(config.proxyBaseUrl+'/capabilities',{method:'POST',headers:{Authorization:'Bearer '+config.sessionToken,'Content-Type':'application/json'},body:JSON.stringify({projectId:config.projectId,mode:'write',env:'preview',apiIds:['customers'],ttlSec:60})});blocked=response.status===403;}catch{blocked=true;}return {blocked,probes:(globalThis as any).__TOI_BOUNDARY_PROBE__,roles:session.roles,sessionToken:config.sessionToken};});
console.log('D preview issuance boundary:',JSON.stringify({roles:security.roles,probes:security.probes,authenticatedCapabilityBlocked:security.blocked}));
expect(security.probes).toHaveLength(2);expect(security.probes.map((probe:any)=>probe.endpoint)).toEqual(['/dev/session','/capabilities']);for(const probe of security.probes){expect(probe.tokenObtained).toBe(false);expect(probe.blocked).toBe(true);}expect(security.blocked).toBe(true);expect(security.roles).toEqual(['viewer']);await frame(page).getByLabel('조회 사유').fill('고객 문의 확인');await frame(page).getByRole('button',{name:'고객 상태를 정지로 변경'}).click();await expect(frame(page).getByRole('alert')).toContainText('쓰기 권한');const attempt=(await snapshot(page)).lastCommit.token.attemptId;await page.getByRole('checkbox',{name:'쓰기 테스트 허용'}).check();await expect.poll(async()=> (await snapshot(page)).lastCommit.token.attemptId).not.toBe(attempt);expect(await frame(page).locator('body').evaluate(()=> (globalThis as any).__TOI_FETCH_CONFIG__.sessionToken)).toBe(security.sessionToken);await frame(page).getByLabel('조회 사유').fill('고객 상태 변경 확인');await frame(page).getByRole('button',{name:'고객 상태를 정지로 변경'}).click();await expect(frame(page).getByRole('status')).toContainText('상태를 정지로 바꿨어요');await expect.poll(async()=>{await page.evaluate(()=> (window as any).studio.loadAudit());return (await snapshot(page)).audit.some((x:any)=>x.method==='PATCH'&&x.decision==='allowed');}).toBe(true);});
test('E: 두 탭 CAS 충돌과 최신 내용 다시 불러오기',async({page,context})=>{await create(page);const tab=await context.newPage();await tab.goto(page.url());await commit(tab,1);await Promise.all([page.getByLabel('소스 코드').fill(plain('첫 탭')),tab.getByLabel('소스 코드').fill(plain('둘째 탭'))]);await Promise.all([page.getByRole('button',{name:'저장하고 반영'}).click(),tab.getByRole('button',{name:'저장하고 반영'}).click()]);await expect.poll(async()=>Number((await snapshot(page)).conflict)+Number((await snapshot(tab)).conflict)).toBe(1);const loser=(await snapshot(page)).conflict?page:tab;await expect(loser.getByRole('alert')).toContainText('다른 탭에서 먼저 저장');await loser.getByRole('button',{name:'최신 내용 불러오기'}).click();await expect.poll(async()=> (await snapshot(loser)).project.revision).toBe(2);await tab.close();});
test('F: 사내 useToast와 앱 React 인스턴스 공유',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await create(page);await save(page,`import React from 'react';import {ToastProvider,useToast,reactInstance} from '@toi/tds';function Content(){const {toast}=useToast();return <><p>{React===(reactInstance.default??reactInstance)?'동일 React':'React 불일치'}</p><button onClick={()=>toast('토스트 성공')}>알림 띄우기</button></>}export default function App(){return <ToastProvider><Content/></ToastProvider>}`);await commit(page,2);await expect(frame(page).getByText('동일 React')).toBeVisible();await frame(page).getByRole('button',{name:'알림 띄우기'}).click();await expect(frame(page).getByText('토스트 성공')).toBeVisible();expect(errors).toEqual([]);expect((await snapshot(page)).events.filter((x:any)=>x.type==='runtime_failed')).toEqual([]);});
