import http from 'node:http';import fs from'node:fs';import path from'node:path';import {chromium}from'playwright-core';
const root=process.cwd(), samples=[], embeddings=[];
function handler(req,res){const u=new URL(req.url,'http://localhost');const mode=u.searchParams.get('mode');if(mode==='iso'||mode==='credentialless'){res.setHeader('Cross-Origin-Opener-Policy','same-origin');res.setHeader('Cross-Origin-Embedder-Policy',mode==='iso'?'require-corp':'credentialless')}res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','no-store');
if(u.pathname==='/'){res.setHeader('Content-Type','text/html');return res.end('<!doctype html><div id="root"></div>')}
if(u.pathname==='/child'){if(u.searchParams.has('coep'))res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(u.searchParams.has('corp'))res.setHeader('Cross-Origin-Resource-Policy','cross-origin');res.setHeader('Content-Type','text/html');return res.end('<script>parent.postMessage({childReady:true,iso:crossOriginIsolated},"*")</script>')}
const f=path.resolve(root,'.'+decodeURIComponent(u.pathname));res.setHeader('Cross-Origin-Embedder-Policy','require-corp');if(!f.startsWith(root+'/')){res.statusCode=403;return res.end()}try{res.setHeader('Content-Type',f.endsWith('.wasm')?'application/wasm':f.endsWith('.html')?'text/html':f.endsWith('.json')?'application/json':'text/javascript');res.end(fs.readFileSync(f))}catch{res.statusCode=404;res.end('missing '+f)}}
const server=http.createServer(handler),child=http.createServer(handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));await new Promise(r=>child.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port,other='http://127.0.0.1:'+child.address().port;
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-first-run'],env:{...process.env,TMPDIR:root+'/.tmp'}});
try{for(const mode of ['plain','iso'])for(const name of ['esbuild-wasm','esbuild-full','swc-wasm','sucrase','babel','oxc-wasm','rolldown-browser'])for(let repeat=1;repeat<=3;repeat++){
const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/?mode='+mode);let result;try{result=await page.evaluate(async name=>await Promise.race([(await import('/browser-case.mjs')).run(name),new Promise(r=>setTimeout(()=>r({error:'timeout 45s'}),45000))]),name)}catch(e){result={error:e.message}}samples.push({mode,repeat,...result,pageErrors:errors});console.log(mode,name,repeat,result);await context.close()}
for(const parent of ['iso','credentialless'])for(const cfg of [{name:'plain',q:''},{name:'CORP-only',q:'corp=1'},{name:'COEP',q:'coep=1'},{name:'credentialless-iframe',q:'',credentialless:true},{name:'COEP-allow',q:'coep=1',allow:true},{name:'COEP+CORP',q:'coep=1&corp=1'},{name:'COEP+CORP+allow',q:'coep=1&corp=1',allow:true}])for(let repeat=1;repeat<=3;repeat++){const page=await browser.newPage();await page.goto(origin+'/?mode='+parent);const result=await page.evaluate(({other,cfg})=>new Promise(resolve=>{let done=false;const finish=r=>{if(!done){done=true;resolve({parentIsolated:crossOriginIsolated,...r})}};addEventListener('message',e=>{if(e.data?.childReady)finish({loaded:true,childIsolated:e.data.iso})});const frame=document.createElement('iframe');if(cfg.credentialless)frame.credentialless=true;if(cfg.allow)frame.allow='cross-origin-isolated';frame.src=other+'/child?'+cfg.q;document.body.append(frame);setTimeout(()=>finish({loaded:false}),800)}),{other,cfg});embeddings.push({parent,case:cfg.name,repeat,...result});await page.close()}
fs.writeFileSync('evidence/browser-results.json',JSON.stringify({browser:browser.version(),samples,embeddings},null,2));
}finally{await browser.close();server.close();child.close()}
