import fs from 'node:fs';import {performance} from 'node:perf_hooks';import {spawnSync} from 'node:child_process';import os from 'node:os';import {files,esOptions,rollPlugin} from './fixtures.mjs';
const names=['esbuild-wasm','esbuild-full','swc-wasm','sucrase','babel','oxc-native','oxc-wasm','rolldown-browser'];
if(!process.argv[2]){const out={environment:{date:new Date().toISOString(),os:os.release(),cpu:os.cpus()[0].model,node:process.version},samples:[]};for(const name of names)for(let repeat=1;repeat<=3;repeat++){const p=spawnSync(process.execPath,['bench-node.mjs',name],{encoding:'utf8',timeout:60000});let row;try{row=JSON.parse(p.stdout)}catch{row={name,error:p.stderr.slice(-3000),stdout:p.stdout,status:p.status}}out.samples.push({repeat,...row});console.log(name,repeat,row)}fs.writeFileSync('evidence/node-results.json',JSON.stringify(out,null,2));process.exit()}
const name=process.argv[2],vfs={...files},row={name};let t=performance.now();
try{
 let mod,transform;
 if(name==='esbuild-wasm'||name==='esbuild-full'){mod=await import('esbuild-wasm');await mod.initialize({});row.js_initialize_ms=performance.now()-t;const ready=performance.now();await mod.transform('export {}',{loader:'js'});row.wasm_ready_probe_ms=performance.now()-ready;row.module_ready_ms=performance.now()-t;if(name==='esbuild-full'){t=performance.now();await mod.build(esOptions(vfs));row.first_full_bundle_ms=performance.now()-t;vfs['/App.tsx']+='\n// edit';t=performance.now();await mod.build(esOptions(vfs));row.second_full_bundle_ms=performance.now()-t;}else{t=performance.now();const ctx=await mod.context(esOptions(vfs));await ctx.rebuild();row.context_first_bundle_ms=performance.now()-t;vfs['/App.tsx']=vfs['/App.tsx'].replace("useState('')","useState('User 1')");t=performance.now();await ctx.rebuild();row.incremental_rebuild_ms=performance.now()-t;await ctx.dispose();}mod.stop()}
 else if(name==='rolldown-browser'){mod=await import('@rolldown/browser');row.module_ready_ms=performance.now()-t;const run=async()=>{const b=await mod.rolldown({input:'/index.tsx',plugins:[rollPlugin(vfs)],transform:{jsx:{runtime:'automatic'}}});await b.generate({format:'esm'});await b.close()};t=performance.now();await run();row.first_full_bundle_ms=performance.now()-t;vfs['/App.tsx']+='\n// edited';t=performance.now();await run();row.second_full_bundle_ms=performance.now()-t}
 else{if(name==='swc-wasm'){mod=await import('@swc/wasm');transform=(f,s)=>mod.transformSync(s,{filename:f,jsc:{parser:{syntax:'typescript',tsx:f.endsWith('tsx')},transform:{react:{runtime:'automatic'}},target:'es2020'},module:{type:'es6'}})}if(name==='sucrase'){mod=await import('sucrase');transform=(f,s)=>mod.transform(s,{filePath:f,transforms:['typescript','jsx'],jsxRuntime:'automatic'})}if(name==='babel'){mod=await import('@babel/standalone');transform=(f,s)=>(mod.default||mod).transform(s,{filename:f,presets:[['typescript',{}],['react',{runtime:'automatic'}]]})}if(name.startsWith('oxc')){mod=await import(name==='oxc-native'?'oxc-transform':'@oxc-transform/binding-wasm32-wasi');transform=(f,s)=>mod.transformSync(f,s,{jsx:{runtime:'automatic'}})}row.module_ready_ms=performance.now()-t;t=performance.now();for(const [f,s]of Object.entries(vfs))await transform(f,s);row.first_transform_all_ms=performance.now()-t;t=performance.now();for(const [f,s]of Object.entries(vfs))await transform(f,s+'\n// edited');row.second_transform_all_ms=performance.now()-t}
}catch(e){row.error=e?.stack||String(e)}console.log(JSON.stringify(row));process.exit();
