import fs from'node:fs';import path from'node:path';import http from'node:http';import {build}from'esbuild';import {chromium}from'playwright-core';
const root=process.cwd(),dir='public/singleton';fs.mkdirSync(dir,{recursive:true});const opts={bundle:true,platform:'browser',format:'esm',jsx:'automatic',define:{'process.env.NODE_ENV':'"production"'},logLevel:'silent'};
const entries={'react':'react','jsx-runtime':'react/jsx-runtime','react-dom':'react-dom','react-dom-client':'react-dom/client','query':'@tanstack/react-query'};const external=['react','react/jsx-runtime','react-dom','@tanstack/react-query'];
for(const[name,entry]of Object.entries(entries)){const ns=await import(entry),api=ns.default??ns;const keys=[...new Set([...Object.keys(ns),...Object.keys(api)])].filter(k=>k!=='default'&&k!=='__esModule'&&/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k));const source=`import * as ns from '${entry}'; const api=ns.default??ns;export default api;`+keys.map(k=>`export const ${k}=api.${k}??ns.${k};`).join('');await build({...opts,stdin:{contents:source,resolveDir:root},plugins:[{name:'exact-peer-externals',setup(b){b.onResolve({filter:/.*/},a=>external.includes(a.path)&&a.path!==entry?(a.kind==='require-call'?{path:a.path,namespace:'peer-shim'}:{path:a.path,external:true}):null);b.onLoad({filter:/.*/,namespace:'peer-shim'},a=>({contents:`import * as peer from '${a.path}'; module.exports=peer.default??peer;`,loader:'js'}))}}],outfile:dir+'/'+name+'.js'});}
const makePkg=n=>`import React,{useState,useEffect}from'react';import {useQueryClient,useQuery}from'@tanstack/react-query';export const reactRef=React;export function Widget(){const [n,setN]=useState(0);const client=useQueryClient();const q=useQuery({queryKey:['shared'],queryFn:async()=>{globalThis.fetches++;return 'shared-value'},staleTime:Infinity});useEffect(()=>{globalThis.clients.push(client)},[client]);return <button id="${n}" onClick={()=>setN(n+1)}>${n}:{n}:{q.data}</button>}`;
for(const name of ['A','B'])await build({...opts,stdin:{contents:makePkg(name),loader:'tsx',resolveDir:root},external,outfile:dir+'/'+name+'.js'});
// Deliberate control: the independently bundled package embeds another React and Query context.
await build({...opts,stdin:{contents:makePkg('B'),loader:'tsx',resolveDir:root},outfile:dir+'/B-bad.js'});
for(const mode of ['good','bad']){
const map={imports:{react:'./react.js','react/jsx-runtime':'./jsx-runtime.js','react-dom':'./react-dom.js','react-dom/client':'./react-dom-client.js','@tanstack/react-query':'./query.js','pkg-a':'./A.js','pkg-b':mode==='good'?'./B.js':'./B-bad.js'}};
fs.writeFileSync(dir+'/'+mode+'.html',`<!doctype html><div id="root"></div><script type="importmap">${JSON.stringify(map)}</script><script type="module">import React from'react';import {createRoot}from'react-dom/client';import {QueryClient,QueryClientProvider}from'@tanstack/react-query';import {Widget as A,reactRef as ar}from'pkg-a';import {Widget as B,reactRef as br}from'pkg-b';window.fetches=0;window.clients=[];window.qc=new QueryClient();window.identity={appA:React===ar,appB:React===br,AB:ar===br};createRoot(document.getElementById('root')).render(React.createElement(QueryClientProvider,{client:qc},React.createElement(React.Fragment,null,React.createElement(A),React.createElement(B))));</script>`)}
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+req.url);res.setHeader('Content-Type',f.endsWith('.html')?'text/html':'text/javascript');if(f.startsWith(root+'/'))try{return res.end(fs.readFileSync(f))}catch{}res.statusCode=404;res.end()});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',env:{...process.env,TMPDIR:root+'/.tmp'}});const samples=[];
try{for(const mode of ['good','bad'])for(let repeat=1;repeat<=3;repeat++){const context=await browser.newContext(),page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.goto('http://127.0.0.1:'+server.address().port+'/'+dir+'/'+mode+'.html');let hookClick=false;try{await page.locator('#A').waitFor({timeout:2000});await page.locator('#A').click();await page.waitForFunction(()=>document.querySelector('#A').textContent.includes('A:1:shared-value'),null,{timeout:2000});hookClick=true}catch{}const row=await page.evaluate(()=>({identity:window.identity,clients:window.clients?.length,queryClientShared:window.clients?.length===2&&window.clients.every(c=>c===window.qc),fetches:window.fetches,text:document.body.innerText}));samples.push({mode,repeat,...row,hookClick,errors,requests});await context.close()}fs.writeFileSync('evidence/singleton-results.json',JSON.stringify({browser:browser.version(),samples},null,2));console.log(samples.map(({requests,...x})=>({...x,moduleRequests:requests.filter(u=>u.endsWith('.js')).length})))}finally{await browser.close();server.close()}
