nodeLinker: node-modules
enableGlobalCache: false
enableMirror: false
cacheFolder: /private/tmp/claude-501/-Users-psw-orca-workspaces-admin-ui-sargassum/4f10a63d-b5f0-49da-96ed-bc9d41509e2a/scratchpad/toss-admin/poc/install-bench/yarn-berry-1/.cache
globalFolder: /private/tmp/claude-501/-Users-psw-orca-workspaces-admin-ui-sargassum/4f10a63d-b5f0-49da-96ed-bc9d41509e2a/scratchpad/toss-admin/poc/install-bench/yarn-berry-1/.global
enableTelemetry: false
npmRegistryServer: "https://registry.npmjs.org"
