import {chromium,expect,type Page} from '@playwright/test';
import {randomUUID} from 'node:crypto';import{mkdir,mkdtemp,rm,writeFile}from'node:fs/promises';import path from'node:path';import os from'node:os';import{fileURLToPath}from'node:url';
import{PackageBuilder}from'../services/deps-builder/src/builder.ts';import{createApp}from'../services/deps-builder/src/server.ts';import{MinioStore}from'../services/deps-builder/src/store.ts';
import{marker,request}from'./app.mjs';
const root=fileURLToPath(new URL('.',import.meta.url));process.chdir(root);await import('./build.mjs');await mkdir('.cache',{recursive:true});
const browser=await chromium.launch({channel:'chrome'});const samples:any[]=[];
async function pageAt(url:string){const context=await browser.newContext();const page=await context.newPage();const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Network.clearBrowserCache');await page.goto('http://localhost:5173'+url);await page.waitForFunction(()=> (window as any).benchReady);return{context,page};}
async function endpoint(page:Page,text:string){await expect.poll(async()=>{for(const frame of page.frames().slice(1)){if(await frame.getByRole('heading',{name:text,exact:true}).isVisible().catch(()=>false))return true;}return false;},{timeout:180000,intervals:[10,25,50]}).toBe(true);const frame=page.frames().slice(1).find(f=>f.url().includes('5174')||f.url().includes('csb.app')||f.url().includes('sandpack'))!;await frame.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));return page.evaluate(()=>performance.now()-(window as any).benchStart);}
async function persist(){const keys=['sandpackColdMs','toiColdMs','toiWarmMs','toiEditMs'];const medians=Object.fromEntries(keys.map(key=>[key,samples.filter(s=>typeof s[key]==='number').map(s=>s[key]).sort((a,b)=>a-b)[1]??null]));await writeFile('results.json',JSON.stringify({measuredAt:new Date().toISOString(),environment:{node:process.version,chrome:browser.version(),os:os.platform(),arch:os.arch(),cpu:os.cpus()[0].model},request,conditions:{endpoint:'Visible benchmark h1 in preview DOM then 2 requestAnimationFrame callbacks; parent performance.now monotonic clock',start:'After host helper JS is loaded, before mounting Sandpack or creating PreviewRuntime and requesting dependency set; navigation and host JS download excluded equally',network:'Local HTTP services; Sandpack public remote bundler and npm CDN over ordinary internet, no artificial throttling; OS, DNS and remote CDN caches not cleared',sandpack:'New browser context and Network.clearBrowserCache each trial; public React 19.3.0 only, HTML table; bundler server cache cannot be cleared',toiCold:'New MinIO bucket, empty local Yarn cache and dependency workspace per trial; dependency POST miss must return 202; fresh browser context and cleared HTTP cache; React plus private @toi/tds Table',toiWarm:'Same dependency artifact; POST hit must return 200; new browser context and cleared HTTP cache; fresh Worker/WASM initialization',toiEdit:'Same runtime, retained Worker/esbuild context and browser dependency cache; edit source to committed visible marker; no package lookup',renderDifference:'TOI uses private @toi/tds Table; Sandpack uses equivalent plain HTML table with same 20 masked rows, no private package; not an equal dependency workload'},samples,medians},null,2)+'\n');}
try{for(let repeat=1;repeat<=3;repeat++){
 const sample:any={repeat};samples.push(sample);const sand=await pageAt('/sandpack.html');try{await sand.page.evaluate(()=> (window as any).startBench());sample.sandpackColdMs=await endpoint(sand.page,marker);console.log('Sandpack',repeat,sample.sandpackColdMs);}catch(error){sample.sandpackError=String(error);console.error('Sandpack failed',repeat,String(error).slice(0,300));}finally{await sand.context.close();await persist();}
 const store=new MinioStore('toi-full-bench-'+randomUUID());await store.init();const cacheRoot=await mkdtemp(path.join(root,'.cache/trial-'));const builder=new PackageBuilder(store,{cacheRoot});const server=createApp(builder);await new Promise<void>(resolve=>server.listen(0,resolve));builder.publicUrl='http://localhost:'+(server.address() as any).port;
 try{
  for(const cold of [true,false]){const {page,context}=await pageAt('/bench.html');try{const pending=page.evaluate(base=>(window as any).startBench(base),builder.publicUrl);await pending;const duration=await endpoint(page,marker);const status=await page.evaluate(()=>(window as any).benchCacheStatus);if(status!==(cold?202:200))throw new Error(`Expected ${cold?'miss':'hit'}, got ${status}`);sample[cold?'toiColdMs':'toiWarmMs']=duration;sample[cold?'coldHttpStatus':'warmHttpStatus']=status;
   if(!cold){await page.evaluate(()=>(window as any).editBench());sample.toiEditMs=await endpoint(page,marker+' 수정');}
  }finally{await context.close();await persist();}}
  console.log('TOI',repeat,sample.toiColdMs,sample.toiWarmMs,sample.toiEditMs);
 }finally{await Promise.all(builder.builds.values());server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));const objects:string[]=[];for await(const object of store.client.listObjectsV2(store.bucket,'',true))if(object.name)objects.push(object.name);if(objects.length)await store.client.removeObjects(store.bucket,objects);await store.client.removeBucket(store.bucket);await rm(cacheRoot,{recursive:true,force:true});}
}}finally{await persist();await browser.close();}
if(samples.some(s=>s.sandpackError))process.exitCode=1;
